// v5-lunch-fix
function _pkgClick(el){var pid=el.dataset.pid;var p=window._pkgMap&&window._pkgMap[pid];if(!p){alert('Pacote nao encontrado');return;}openPkgBooking(p);}
var PKB={pkg:null,totalSessions:0,currentSession:0,sessions:[],calM:new Date().getMonth(),calY:new Date().getFullYear(),selDate:null,selDateISO:null,selTime:null,busySlots:[]};
function calcSessions(f,v){var fM={'Semanal':4,'Quinzenal':2,'Mensal':1};var vM={'Mensal':1,'Bimestral':2,'Semestral':6};return(fM[f]||1)*(vM[v]||1);}
function openPkgBooking(p){PKB.pkg=p;PKB.sessions=[];PKB.currentSession=0;PKB.totalSessions=calcSessions(p.frequencia,p.validade);PKB.calM=new Date().getMonth();PKB.calY=new Date().getFullYear();PKB.selDate=null;PKB.selDateISO=null;PKB.selTime=null;PKB.busySlots=[];document.getElementById('pkb-title').textContent=p.name;document.getElementById('pkb-subtitle').textContent=(p.frequencia||'')+' - Validade '+(p.validade||'')+' - '+PKB.totalSessions+' sessoes';document.getElementById('pkb-cal-area').style.display='block';document.getElementById('pkb-final').style.display='none';var btn=document.getElementById('pkb-btn-next');btn.disabled=true;btn.textContent='Proxima sessao';btn.onclick=pkbNext;document.getElementById('pkb-btn-back').style.display='none';pkbUpdateProgress();pkbRenderDots();pkbRenderCal();if(openMod)openMod('mod-pkg-book');
  // Load barbers into select
  setTimeout(function(){
    var sel=document.getElementById('pkb-barber');
    var _S=window.S||(typeof S!=='undefined'?S:null);
    var _db=window.db||(typeof db!=='undefined'?db:null);
    if(sel&&_S&&_S.shopId&&_db){
      _db.from('barbers').select('id,name').eq('shop_id',_S.shopId).eq('active',true).order('name').then(function(r){
        var barbers=(r&&r.data)||[];
        sel.innerHTML='<option value="">A definir</option>'+barbers.map(function(b){return '<option value="'+b.id+'">'+b.name+'</option>';}).join('');
      });
    }
  },100);}
function pkbUpdateProgress(){var cur=PKB.currentSession+1,tot=PKB.totalSessions;document.getElementById('pkb-progress').textContent='Sessao '+cur+' de '+tot;var btn=document.getElementById('pkb-btn-next');btn.disabled=!(PKB.selDate&&PKB.selTime);btn.textContent=(cur===tot)?'Ver resumo':'Proxima sessao';}
function pkbRenderDots(){var el=document.getElementById('pkb-dots'),html='';for(var i=0;i<PKB.totalSessions;i++){var done=i<PKB.currentSession,active=i===PKB.currentSession;var bg=done?'#27AE60':active?'#C9A84C':'#2E2E2E';var col=(done||active)?'#0E0E0E':'#9A9080';html+='<div style=width:26px;height:26px;border-radius:50%;background:'+bg+';display:flex;align-items:center;justify-content:center;font-size:10px;font-weight:700;color:'+col+'>'+(i+1)+'</div>';if(i<PKB.totalSessions-1)html+='<div style=flex:1;height:1.5px;background:'+(done?'#27AE60':'#2E2E2E')+';min-width:6px;max-width:20px;align-self:center></div>';}el.innerHTML=html;}
var MTHS_P=['Janeiro','Fevereiro','Marco','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
function pkbChMon(d){PKB.calM+=d;if(PKB.calM>11){PKB.calM=0;PKB.calY++;}if(PKB.calM<0){PKB.calM=11;PKB.calY--;}pkbRenderCal();}
function pkbRenderCal(){var g=document.getElementById('pkb-cal-grid'),lbl=document.getElementById('pkb-cal-lbl');if(!g||!lbl)return;lbl.textContent=MTHS_P[PKB.calM]+' '+PKB.calY;var dn=['Dom','Seg','Ter','Qua','Qui','Sex','Sab'];var fd=new Date(PKB.calY,PKB.calM,1).getDay(),dim=new Date(PKB.calY,PKB.calM+1,0).getDate();var now=new Date(),td=now.getDate(),tm=now.getMonth(),ty=now.getFullYear();var minGap=PKB.pkg&&PKB.pkg.frequencia==='Semanal'?7:PKB.pkg&&PKB.pkg.frequencia==='Quinzenal'?14:28;var lastISO=PKB.sessions.length>0?PKB.sessions[PKB.sessions.length-1].dateISO:null;var h=dn.map(function(d){return'<div class=cal-dn>'+d+'</div>';}).join('');for(var i=0;i<fd;i++)h+='<div></div>';for(var d2=1;d2<=dim;d2++){var dt=new Date(PKB.calY,PKB.calM,d2),dow=dt.getDay();var iso=PKB.calY+'-'+String(PKB.calM+1).padStart(2,'0')+'-'+String(d2).padStart(2,'0');var lbl2=d2+' '+MTHS_P[PKB.calM].slice(0,3);var past=dt<new Date(ty,tm,td);var used=PKB.sessions.some(function(s){return s.dateISO===iso;});var diff=lastISO?(new Date(iso)-new Date(lastISO))/86400000:999;var tooClose=lastISO&&diff<minGap&&diff>0;var cls='cal-d';if(past||used||tooClose)cls+=' past';else if(dow===0)cls+=' off';else cls+=' av';if(d2===td&&PKB.calM===tm&&PKB.calY===ty)cls+=' tod';if(PKB.selDateISO===iso)cls+=' sel';var canClick=!past&&!used&&!tooClose&&dow!==0;var oc=canClick?' data-lbl="'+lbl2+'" data-iso="'+iso+'" onclick="pkbCellClick(this)"':'';h+='<div class="'+cls+'"'+oc+'>'+d2+'</div>';}g.innerHTML=h;}
async function pkbSelDate(el,label,iso){document.querySelectorAll('#pkb-cal-grid .cal-d').forEach(function(d){d.classList.remove('sel');});el.classList.add('sel');PKB.selDate=label;PKB.selDateISO=iso;PKB.selTime=null;document.getElementById('pkb-tg').innerHTML='<div style="text-align:center;padding:10px"><div class="spin"></div></div>';try{if(db){var r=await db.from('appointments').select('appointment_time,total_duration_minutes,barber_id').eq('appointment_date',iso).eq('shop_id',S.shopId).neq('status','cancelled');var allAppts=r.data||[];var barbSel=document.getElementById('pkb-barber');var selBarberId=barbSel&&barbSel.value?barbSel.value:null;if(selBarberId){PKB.busySlots=allAppts.filter(function(a){return a.barber_id===selBarberId||!a.barber_id;}).map(function(a){return{time:a.appointment_time.slice(0,5),dur:Number(a.total_duration_minutes)||30};});}else{var barbR=await db.from('barbers').select('id').eq('shop_id',S.shopId).eq('active',true);var barberIds=(barbR.data||[]).map(function(b){return b.id;});var numBarbers=barberIds.length||1;var slotMap={};allAppts.forEach(function(a){var t=a.appointment_time.slice(0,5);var dur=Number(a.total_duration_minutes)||30;var parts=t.split(':');var startMin=Number(parts[0])*60+Number(parts[1]);for(var min=startMin;min<startMin+dur;min+=5){var key=String(Math.floor(min/60)).padStart(2,'0')+':'+String(min%60).padStart(2,'0');if(!slotMap[key])slotMap[key]=new Set();if(a.barber_id){slotMap[key].add(a.barber_id);}else{barberIds.forEach(function(bid){slotMap[key].add(bid);});}}});PKB.busySlots=[];Object.keys(slotMap).forEach(function(key){if(slotMap[key].size>=numBarbers){PKB.busySlots.push({time:key,dur:5});}});}try{var blkR=await db.from('blocked_slots').select('start_time,end_time').eq('shop_id',S.shopId).eq('block_date',iso);(blkR.data||[]).forEach(function(b){var bS=b.start_time.slice(0,5),bE=b.end_time.slice(0,5);var toM2=function(t2){var p2=t2.split(':').map(Number);return p2[0]*60+p2[1];};var sm=toM2(bS),em=toM2(bE);for(var m=sm;m<em;m+=5){PKB.busySlots.push({time:String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0'),dur:5});}});}catch(e2){}}}catch(e){PKB.busySlots=[];}pkbRenderTimes();pkbUpdateProgress();}
function pkbRenderTimes(){var g=document.getElementById('pkb-tg');if(!g)return;var shop=(S&&S.shop)||{};var open=(shop.opening_time||'09:00').slice(0,5),close=(shop.closing_time||'20:00').slice(0,5);var lunchStart=shop.lunch_start?(shop.lunch_start.slice(0,5)):'';var lunchEnd=shop.lunch_end?(shop.lunch_end.slice(0,5)):'';var slot=Number(shop.slot_duration)||30;var toMin=function(t){var p=t.split(':').map(Number);return p[0]*60+p[1];};var toStr=function(m){return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');};var lsM=lunchStart?toMin(lunchStart):null;var leM=lunchEnd?toMin(lunchEnd):null;var openM=toMin(open),closeM=toMin(close);var occupied=[];(PKB.busySlots||[]).forEach(function(b){var bStart=toMin(b.time);occupied.push({start:bStart,end:bStart+b.dur});});if(lsM!==null&&leM!==null)occupied.push({start:lsM,end:leM,lunch:true});occupied.sort(function(a,b){return a.start-b.start;});var merged=[];occupied.forEach(function(o){if(merged.length&&o.start<merged[merged.length-1].end){merged[merged.length-1].end=Math.max(merged[merged.length-1].end,o.end);if(o.lunch)merged[merged.length-1].lunch=true;}else{merged.push({start:o.start,end:o.end,lunch:o.lunch||false});}});var slots=[];var cursor=openM;merged.forEach(function(block){while(cursor+slot<=block.start&&cursor+slot<=closeM){slots.push({time:toStr(cursor)});cursor+=slot;}if(block.end>cursor)cursor=block.end;});while(cursor+slot<=closeM){slots.push({time:toStr(cursor)});cursor+=slot;}if(!slots.length){g.innerHTML='<div style="color:#9A9080;padding:10px">Sem horarios disponíveis.</div>';return;}var html='';if(lsM&&leM){var manha=slots.filter(function(s){return toMin(s.time)<lsM;});var tarde=slots.filter(function(s){return toMin(s.time)>=leM;});if(manha.length)html+='<div style="grid-column:span 4;font-size:11px;font-weight:700;color:#C9A84C;letter-spacing:1px;padding:4px 0 6px;text-transform:uppercase">☀ Manhã</div>'+manha.map(function(s){return'<div class="ts'+(PKB.selTime===s.time?' sel':'')+'" data-time="'+s.time+'" onclick="pkbTimeClick(this)">'+s.time+'</div>';}).join('');html+='<div style="grid-column:span 4;font-size:11px;color:#9A9080;padding:6px 0 4px;display:flex;align-items:center;gap:8px"><div style="flex:1;height:1px;background:#2E2E2E"></div>🍽 Almoço '+lunchStart+'–'+lunchEnd+'<div style="flex:1;height:1px;background:#2E2E2E"></div></div>';if(tarde.length)html+='<div style="grid-column:span 4;font-size:11px;font-weight:700;color:#C9A84C;letter-spacing:1px;padding:4px 0 6px;text-transform:uppercase">🌤 Tarde</div>'+tarde.map(function(s){return'<div class="ts'+(PKB.selTime===s.time?' sel':'')+'" data-time="'+s.time+'" onclick="pkbTimeClick(this)">'+s.time+'</div>';}).join('');}else{html=slots.map(function(s){return'<div class="ts'+(PKB.selTime===s.time?' sel':'')+'" data-time="'+s.time+'" onclick="pkbTimeClick(this)">'+s.time+'</div>';}).join('');}g.innerHTML=html;}
function pkbSelTime(el,t){document.querySelectorAll('#pkb-tg .ts').forEach(function(x){x.classList.remove('sel');});el.classList.add('sel');PKB.selTime=t;pkbUpdateProgress();}
function pkbNext(){if(!PKB.selDate||!PKB.selTime)return;PKB.sessions.push({date:PKB.selDate,dateISO:PKB.selDateISO,time:PKB.selTime});PKB.selDate=null;PKB.selDateISO=null;PKB.selTime=null;if(PKB.sessions.length>=PKB.totalSessions){pkbShowFinal();return;}PKB.currentSession++;pkbUpdateProgress();pkbRenderDots();pkbRenderCal();document.getElementById('pkb-tg').innerHTML='<div style=color:#9A9080;padding:10px>Selecione uma data</div>';document.getElementById('pkb-btn-back').style.display='block';}
function pkbBack(){if(PKB.sessions.length===0)return;document.getElementById('pkb-cal-area').style.display='block';document.getElementById('pkb-final').style.display='none';document.getElementById('pkb-btn-next').onclick=pkbNext;PKB.sessions.pop();PKB.currentSession=PKB.sessions.length;PKB.selDate=null;PKB.selDateISO=null;PKB.selTime=null;if(PKB.currentSession===0)document.getElementById('pkb-btn-back').style.display='none';pkbUpdateProgress();pkbRenderDots();pkbRenderCal();}
function pkbShowFinal(){document.getElementById('pkb-cal-area').style.display='none';document.getElementById('pkb-final').style.display='block';document.getElementById('pkb-progress').textContent='Resumo';document.getElementById('pkb-btn-back').style.display='block';var btn=document.getElementById('pkb-btn-next');btn.textContent='Enviar pelo WhatsApp';btn.disabled=false;btn.onclick=pkbConfirm;var p=PKB.pkg;var sh=PKB.sessions.map(function(s,i){return'<div style=display:flex;align-items:center;gap:10px;padding:6px 0;border-bottom:1px solid #2E2E2E><span style=color:#C9A84C;font-size:11px;font-weight:700;min-width:64px>Sessao '+(i+1)+'</span><span style=font-size:13px>'+s.date+' as '+s.time+'</span></div>';}).join('');document.getElementById('pkb-summary').innerHTML='<div style=font-size:14px;font-weight:700;margin-bottom:6px>'+p.name+'</div><div style=font-size:12px;color:#9A9080;margin-bottom:10px>'+(p.frequencia||'')+' - Validade '+(p.validade||'')+' - '+(fmt?fmt(p.price):p.price)+'</div>'+sh;pkbRenderDots();}
async function pkbConfirm(){var name=document.getElementById('pkb-name').value.trim();var phone=document.getElementById('pkb-phone').value.trim();if(!name||!phone){if(toast)toast('Preencha nome e WhatsApp.','err');return;}var p=PKB.pkg,shop=(S&&S.shop)||{};var waNum=(shop.whatsapp||'').replace(/[^0-9]/g,'');if(!waNum){if(toast)toast('Configure o WhatsApp.','err');return;}var pgid='pkg-'+Date.now()+'-'+Math.random().toString(36).slice(2,8);var chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';var ref='PKT-';for(var ri=0;ri<6;ri++)ref+=chars[Math.floor(Math.random()*chars.length)];var tot=PKB.sessions.length;var pkgDur=Number(p.duration_minutes)||30;var appts=PKB.sessions.map(function(s,i){return{shop_id:S&&S.shopId,client_name:name,client_phone:phone,service_name:p.name,service_price:Math.round((p.price/tot)*100)/100,barber_name:(document.getElementById('pkb-barber')&&document.getElementById('pkb-barber').value?document.getElementById('pkb-barber').options[document.getElementById('pkb-barber').selectedIndex].text:'A definir'),barber_id:(document.getElementById('pkb-barber')&&document.getElementById('pkb-barber').value?document.getElementById('pkb-barber').value:null),appointment_date:s.dateISO,appointment_time:s.time,total_duration_minutes:pkgDur,status:'pending',payment_method:'local',payment_status:'pending',package_group_id:pgid,package_ref:ref,package_session_num:i+1,package_total_sessions:tot};});try{if(db)await db.from('appointments').insert(appts);}catch(e){}var LF=String.fromCharCode(10);var msg='*Agendamento de Pacote - BarberOS*'+LF+'*Referencia:* '+ref+LF+LF+'*Pacote:* '+p.name+LF+'*Frequencia:* '+(p.frequencia||'')+LF+'*Validade:* '+(p.validade||'')+LF+'*Valor:* '+(fmt?fmt(p.price):p.price)+LF+LF+'*Sessoes:*'+LF;PKB.sessions.forEach(function(s,i){msg+='  Sessao '+(i+1)+': '+s.date+' as '+s.time+LF;});msg+=LF+'*Cliente:* '+name+LF+'*WhatsApp:* '+phone;var _waLink=document.createElement('a');_waLink.href='https://wa.me/'+waNum+'?text='+encodeURIComponent(msg);_waLink.target='_blank';_waLink.rel='noopener';document.body.appendChild(_waLink);_waLink.click();document.body.removeChild(_waLink);if(closeMod)closeMod('mod-pkg-book');if(toast)toast('Pacote agendado!','ok');}
function pkbCellClick(el){pkbSelDate(el,el.dataset.lbl,el.dataset.iso);}
function pkbTimeClick(el){pkbSelTime(el,el.dataset.time);}